spring.application.name=food-wave-project



server.port= 9090

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/foods
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

###
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=1fa90882c63399
spring.mail.password=ad58f07591f123
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google sozlamalari
spring.security.oauth2.client.registration.google.client-id=880728233237-ee1pq4k1ef8enivsvqjm48aa6an31r14.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/api/oauth2/callback/google
spring.security.oauth2.client.registration.google.scope=email,profile

# Facebook sozlamalari
spring.security.oauth2.client.registration.facebook.client-id=YOUR_FACEBOOK_CLIENT_ID
spring.security.oauth2.client.registration.facebook.client-secret=YOUR_FACEBOOK_CLIENT_SECRET
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8080/api/oauth2/callback/facebook
spring.security.oauth2.client.registration.facebook.scope=email,public_profile

# User info endpoints
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email,picture

