spring.application.name=food-wave-project



server.port= 8080

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/food
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

###
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=7a604379444c39
spring.mail.password=7e6efd86ec294e
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.security.oauth2.client.registration.github.client-id=Ov23liAJSi3CFJsPwS3w
#spring.security.oauth2.client.registration.github.client-secret=4be96e88372d798cec5f8e717e2040738036d1c3


spring.security.oauth2.client.registration.google.client-id=450004792370-md2ffot3dlh1nrtmf4diunif6h7881p7.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

#spring.security.oauth2.client.registration.facebook.client-id=YOUR_FACEBOOK_CLIENT_ID
#spring.security.oauth2.client.registration.facebook.client-secret=YOUR_FACEBOOK_CLIENT_SECRET
#spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8080/api/oauth2/callback/facebook


