spring:
  application:
    name: food-wave-project

  datasource:
    url: jdbc:postgresql://localhost:5432/food_wave
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 7a604379444c39
    password: 7e6efd86ec294e
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
